### ISSUE TITLE
Exception `Unexpected #` throws on parsing private fields

### ISSUE THREAD

**Issue by MaximMoiseenko** [mck89/peast#20] opened 2020-03-25 21:43 UTC
Peast\Syntax\Exception with message "Unexpected #" throws then try to parse class code with private property like this one:

```
class ClassPrivateFld {
  #msg = 'hello world'
  get msg() {
    return this.#msg
  }
}
```

**Comment by mck89** [comment] 2020-03-26 10:13
That's the expected behaviour since "Private methods and fields" proposal haven't been included in ECMAScript specification yet and for the same reason there isn't a specification of the fortmat that will be used for that syntax in the  ESTree standard.
I close the issue, but i will implement that syntax when it will be included in the specification.

**Closed by mck89** 2020-03-26 10:13 UTC
