### ISSUE TITLE
Tokenize method very slow on large JS files

### ISSUE THREAD

**Issue by ElectroMW** [mck89/peast#32] opened 2021-04-25 14:10 UTC
Hi there,

This isn't a bug report but more of a request for more information.
I'm finding that for large JS files tokenization is taking 20 or more seconds in some cases.

I'm following the example in the docs, e.g;
$source = "large JS file";
$tokens = Peast\Peast::latest($source, $options)->tokenize();

I was wondering if there was any way I could increase the performance of the tokenize method (including possible code improvements and a pull request)?

Any help or pointers would be much appreciated
ElectroMW

An example of the JS that is taking a long time to tokenize;
https://pastebin.com/v7JALVV7
https://pastebin.com/RnEftpiT

**Comment by mck89** [comment] 2021-04-26 15:22
Honestly i thought it would be slower than 20 seconds for files this large, but i agree that it's a long time to parse a file.
I don't think i can point you anything that can be simply modified to make it faster, it must be investigated to measure the performances of all methods to understand which are the slow points.
Obviously any improvement through PRis welcome, but i keep the issue open to investigate and i will use the code you attached for tests.

**Comment by ElectroMW** [comment] 2021-04-26 15:51
Thanks for the response.
I'll try and do some testing at my end and if I get a useful solution I'll create a pull request.
Interestingly - the generation of AST's on files the same size or bigger is vastly quicker (0.5 sec for comparison) and as far as I can tell, they are both using the same parse() method.

**Comment by mck89** [comment] 2021-06-25 12:49
I've just released a new version with major performance improvements.

I found and corrected 3 main problems:

- The performance issue on the tokenize method was caused by massive calls to array_slice function when the parser state was reset and invalid tokens need to be removed. I've changed it to execute only if the tokens count changed and used array_pop to remove the tokens
- Scanning and parsing could be improved by reordering the internal methods to parse common patterns before others. For example when scanning, strings are less common than identifiers and keywords, so if the scanner checks identifiers and keywords before strings it will be faster most of the time
- Performance could be improved by reducing function calls so:
    - i've changed all the class properties in Token, SourceLocation and Position classes and the position property in Node class to be public, in this way they can be accessed without calling the getter functions
    - i've implemented some checks in the main parsing functions to check the current token before calling internal function, so that they will be called only if necessary

From my tests, using your first script:
- the parsing performance have been improved from 20 to 40% (depending on the hardware and the php version)
- function calls count is changed from 5.5 millions to 2.8 millions
- on a very old (and slow) pc with PHP 5.4 the parsing time changed from 30 seconds to 18
- on a faster pc with PHP 7 the parsing time changed from 0.9 seconds to 0.7
- tokenize and parsing functions take almost the same time now

I close the issue since i think the problem is solved now, please let me know if performance have been improved for you too.

**Closed by mck89** 2021-06-25 12:49 UTC

**Comment by ElectroMW** [comment] 2021-06-28 17:54
Thanks for the update.
Performance is significantly better on my test loads.

A 240KB file on my dev PC (PHP 8 - JIT enabled) took 1.9s to ->parse() and 2.3s to ->tokenize().

Thank you again for the update.
